### ISSUE TITLE
Bug in CharmmTopology class

### ISSUE THREAD

**Issue by madscatt** [madscatt/zazmol#32]
reading hiv1_gag.pdb (min3.pdb) the following incorrect output is displayed.

```
>>> import sasmol.system as system
>>> molecule = system.Molecule('min3.pdb')
reading filename:  min3.pdb
num_atoms =  6730
>>> found  1  model(s) or frame(s)
finished reading frame =  1
>>> molecule.check_charmm_atomic_order_reorganize()
["For residue: GLY_GLYP\nthe atom names doesn't match those in the charmm topology file!\n['N', 'HT1', 'HT2', 'HT3', 'CA', 'HA1', 'HA2', 'HN', 'C', 'O']\n['N', 'HT1', 'HT2', 'HT3', 'CA', 'HA1', 'HA2', 'C', 'O']"]
>>> molecule patch_charmm_residue_atoms('GLY','GLYP')
```

**Comment by madscatt** [comment]
@hailiangzhang ... can you debug this?

**Comment by madscatt** [comment]
This may be an issue with sasmol (in sassie_1.0) only.  The following tar-ball contains a new saspdbrx that should fix this issue in the 1.0 branch.  It also includes a new test for the method responsible for the original bug.  This needs to be carefully tested.

[saspdbrx_and_test.tar.gz](https://github.com/madscatt/zazmol/files/441397/saspdbrx_and_test.tar.gz)

**Comment by madscatt** [comment]
@hailiangzhang ... please compare your line by line changes to that in zazmol/src/python/charmm_topology.py 

This still fails the test with the same error.  Track this down please.

**Comment by hailiangzhang** [comment]
Attached is the modified "charmm_topology.py" to fix bugs reported in this issue.
[charmm_topology.py.tar.gz](https://github.com/madscatt/zazmol/files/454063/charmm_topology.py.tar.gz)

**Comment by madscatt** [comment]
Seems to clean up the error now.  Passes the single test that exists for the charmm_topology module.
